package mx.com.ensitech.proxymodule.utils;

public class GeneralParams {
	public static final String URL_BASE="https://gateway.marvel.com:443";
	public static final String PATH_BASE="/v1/public/characters";
	public static final int TS=1;
	public static final String APIKEY="4381496f3eef33e6baf39c290cabc235";
	public static final String HASH="9082aadc85744dff7dae621c6cf727c1";
	
	public static final String CHARACTERS_GET_ALL = "OK";
	
	public static final String CHARACTER_GET_BY_ID = "{\r\n"
			+ "    \"id\": 1011334,\r\n"
			+ "    \"name\": \"3-D Man\",\r\n"
			+ "    \"description\": \"\",\r\n"
			+ "    \"modified\": \"2014-04-29T14:18:17-0400\",\r\n"
			+ "    \"thumbnail\": {\r\n"
			+ "        \"path\": \"http://i.annihil.us/u/prod/marvel/i/mg/c/e0/535fecbbb9784\",\r\n"
			+ "        \"extension\": \"jpg\"\r\n"
			+ "    },\r\n"
			+ "    \"resourceURI\": \"http://gateway.marvel.com/v1/public/characters/1011334\",\r\n"
			+ "    \"comics\": {\r\n"
			+ "        \"available\": 12,\r\n"
			+ "        \"collectionURI\": \"http://gateway.marvel.com/v1/public/characters/1011334/comics\",\r\n"
			+ "        \"items\": [\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/comics/21366\",\r\n"
			+ "                \"name\": \"Avengers: The Initiative (2007) #14\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/comics/24571\",\r\n"
			+ "                \"name\": \"Avengers: The Initiative (2007) #14 (SPOTLIGHT VARIANT)\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/comics/21546\",\r\n"
			+ "                \"name\": \"Avengers: The Initiative (2007) #15\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/comics/21741\",\r\n"
			+ "                \"name\": \"Avengers: The Initiative (2007) #16\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/comics/21975\",\r\n"
			+ "                \"name\": \"Avengers: The Initiative (2007) #17\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/comics/22299\",\r\n"
			+ "                \"name\": \"Avengers: The Initiative (2007) #18\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/comics/22300\",\r\n"
			+ "                \"name\": \"Avengers: The Initiative (2007) #18 (ZOMBIE VARIANT)\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/comics/22506\",\r\n"
			+ "                \"name\": \"Avengers: The Initiative (2007) #19\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/comics/8500\",\r\n"
			+ "                \"name\": \"Deadpool (1997) #44\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/comics/10223\",\r\n"
			+ "                \"name\": \"Marvel Premiere (1972) #35\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/comics/10224\",\r\n"
			+ "                \"name\": \"Marvel Premiere (1972) #36\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/comics/10225\",\r\n"
			+ "                \"name\": \"Marvel Premiere (1972) #37\"\r\n"
			+ "            }\r\n"
			+ "        ],\r\n"
			+ "        \"returned\": 12\r\n"
			+ "    },\r\n"
			+ "    \"series\": {\r\n"
			+ "        \"available\": 3,\r\n"
			+ "        \"collectionURI\": \"http://gateway.marvel.com/v1/public/characters/1011334/series\",\r\n"
			+ "        \"items\": [\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/series/1945\",\r\n"
			+ "                \"name\": \"Avengers: The Initiative (2007 - 2010)\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/series/2005\",\r\n"
			+ "                \"name\": \"Deadpool (1997 - 2002)\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/series/2045\",\r\n"
			+ "                \"name\": \"Marvel Premiere (1972 - 1981)\"\r\n"
			+ "            }\r\n"
			+ "        ],\r\n"
			+ "        \"returned\": 3\r\n"
			+ "    },\r\n"
			+ "    \"stories\": {\r\n"
			+ "        \"available\": 21,\r\n"
			+ "        \"collectionURI\": \"http://gateway.marvel.com/v1/public/characters/1011334/stories\",\r\n"
			+ "        \"items\": [\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/stories/19947\",\r\n"
			+ "                \"name\": \"Cover #19947\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/stories/19948\",\r\n"
			+ "                \"name\": \"The 3-D Man!\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/stories/19949\",\r\n"
			+ "                \"name\": \"Cover #19949\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/stories/19950\",\r\n"
			+ "                \"name\": \"The Devil's Music!\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/stories/19951\",\r\n"
			+ "                \"name\": \"Cover #19951\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/stories/19952\",\r\n"
			+ "                \"name\": \"Code-Name:  The Cold Warrior!\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/stories/47184\",\r\n"
			+ "                \"name\": \"AVENGERS: THE INITIATIVE (2007) #14\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/stories/47185\",\r\n"
			+ "                \"name\": \"Avengers: The Initiative (2007) #14 - Int\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/stories/47498\",\r\n"
			+ "                \"name\": \"AVENGERS: THE INITIATIVE (2007) #15\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/stories/47499\",\r\n"
			+ "                \"name\": \"Avengers: The Initiative (2007) #15 - Int\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/stories/47792\",\r\n"
			+ "                \"name\": \"AVENGERS: THE INITIATIVE (2007) #16\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/stories/47793\",\r\n"
			+ "                \"name\": \"Avengers: The Initiative (2007) #16 - Int\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/stories/48361\",\r\n"
			+ "                \"name\": \"AVENGERS: THE INITIATIVE (2007) #17\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/stories/48362\",\r\n"
			+ "                \"name\": \"Avengers: The Initiative (2007) #17 - Int\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/stories/49103\",\r\n"
			+ "                \"name\": \"AVENGERS: THE INITIATIVE (2007) #18\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/stories/49104\",\r\n"
			+ "                \"name\": \"Avengers: The Initiative (2007) #18 - Int\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/stories/49106\",\r\n"
			+ "                \"name\": \"Avengers: The Initiative (2007) #18, Zombie Variant - Int\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/stories/49888\",\r\n"
			+ "                \"name\": \"AVENGERS: THE INITIATIVE (2007) #19\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/stories/49889\",\r\n"
			+ "                \"name\": \"Avengers: The Initiative (2007) #19 - Int\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/stories/54371\",\r\n"
			+ "                \"name\": \"Avengers: The Initiative (2007) #14, Spotlight Variant - Int\"\r\n"
			+ "            }\r\n"
			+ "        ],\r\n"
			+ "        \"returned\": 20\r\n"
			+ "    },\r\n"
			+ "    \"events\": {\r\n"
			+ "        \"available\": 1,\r\n"
			+ "        \"collectionURI\": \"http://gateway.marvel.com/v1/public/characters/1011334/events\",\r\n"
			+ "        \"items\": [\r\n"
			+ "            {\r\n"
			+ "                \"resourceURI\": \"http://gateway.marvel.com/v1/public/events/269\",\r\n"
			+ "                \"name\": \"Secret Invasion\"\r\n"
			+ "            }\r\n"
			+ "        ],\r\n"
			+ "        \"returned\": 1\r\n"
			+ "    },\r\n"
			+ "    \"urls\": [\r\n"
			+ "        {\r\n"
			+ "            \"type\": \"detail\",\r\n"
			+ "            \"url\": \"http://marvel.com/characters/74/3-d_man?utm_campaign=apiRef&utm_source=4381496f3eef33e6baf39c290cabc235\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"type\": \"wiki\",\r\n"
			+ "            \"url\": \"http://marvel.com/universe/3-D_Man_(Chandler)?utm_campaign=apiRef&utm_source=4381496f3eef33e6baf39c290cabc235\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"type\": \"comiclink\",\r\n"
			+ "            \"url\": \"http://marvel.com/comics/characters/1011334/3-d_man?utm_campaign=apiRef&utm_source=4381496f3eef33e6baf39c290cabc235\"\r\n"
			+ "        }\r\n"
			+ "    ]\r\n"
			+ "}";
}
